### PR TITLE
Start CONTRIBUTE.md with development-state testing link

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This pull request follows an alternative review procedure, requiring approval from the Technical Steering Committee instead of the Ontology Committee.  It will not trigger requiring a release.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@plbt5 , the result of the gathered TSC input is that this is OK to merge in the "Two-key" pattern.  One person submits, another person merges.  Please feel free to review and merge, and likewise for [PR 86](https://github.com/casework/CASE/pull/86).

**Review by plbt5 — CHANGES_REQUESTED** [review]
The link on line 6 cannot resolve since its domain neither carries a top-level nor a 2nd-level domain name.

**Comment by ajnelson-nist** [comment]
> The link on line 6 cannot resolve since its domain neither carries a top-level nor a 2nd-level domain name.

Ah dear, thank you for pointing that out.  I've pushed a fix.

**Review by plbt5 — APPROVED** [review]
Approved

**Pull request merged**
