### PR TITLE
Ont 363

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
I recommend at least [PR 41](https://github.com/casework/CASE/pull/41/) be merged first to run CI tests.

**Review by plbt5 — DISMISSED** [review]
The change itself is agreed without any identified issue. However, I consider the presence of a definition for a concept (using natural language in `rdfs:comment`) a necessary criterion before taking a concept from the design phase into production. There are several concepts that currently lack such a definition.

**Comment by ajnelson-nist** [comment]
@plbt5 , another proposal that I need to transcribe into a branch carries class definitions.  It's ONT-379 / CP-18.  All of the *classes* in the investigation namespace will have definitions after that (or if not, we need to file a fixer ticket for CASE 0.4.0).  We know we need definitions for the properties.

**Review by plbt5 — COMMENTED** [review]
✔️ Changelog contains CP and ONT request referrals

**Pull request merged**
