### PR TITLE
Ont 413

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
I recommend [PR 41](https://github.com/casework/CASE/pull/41/) be merged first.

**Comment by ajnelson-nist** [comment]
@plbt5 I've fixed the merge conflict.  This is ready for your review.

**Review by plbt5 — DISMISSED** [review]
- ✔️ All suggested prefixes have been carried through; all concepts now carry a prefix. 
- ❌  I have not validated consistency with imported ontology in that all prefixed concepts actually exist. I assume this to be part of the regression test.

**Comment by ajnelson-nist** [comment]
I added a merge commit to address the ChangeLog conflict and update the merge to today.  The material to review is otherwise unchanged, @plbt5 .

**Comment by ajnelson-nist** [comment]
Sorry!  I missed you reviewed.

**Review by plbt5 — APPROVED** [review]

**Comment by plbt5** [comment]
haha, we're workng against each other now :-)

**Comment by ajnelson-nist** [comment]
Re:
> I have not validated consistency with imported ontology in that all prefixed concepts actually exist. I assume this to be part of the regression test.
Yes, these tests exist, though in the [CASE-Examples-QC](https://github.com/ajnelson-nist/CASE-Examples-QC) repository.  There is an automated test there to confirm referenced concepts exist in instance data.  The test was not a committee-approved mechanism, but it has assisted with all examples' quality control to date.  These tests will be incorporating the recently-released [UCO-Utility-Pre-0.6.0-Validator](https://github.com/ucoProject/UCO-Utility-Pre-0.6.0-Validator).

**Pull request merged**
