### PR TITLE
Update Readme.md: ONT-442 Fix broken link

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This picks up from [PR 63](https://github.com/casework/CASE/pull/63).  Sorry for the confusion, @plbt5 .

### CODE REVIEW

**Review by plbt5 — COMMENTED** [review]
*duh* I also forgot to update the changelog...

**Review by plbt5 — APPROVED** [review]

**Review by plbt5 — APPROVED** [review]

**Comment by plbt5** [comment]
I don't think it is necessary for you to apologise for the confusion @ajnelson-nist ; it was me messing it up in the first place ... again :-(

**Comment by plbt5** [comment]
**_@ajnelson-nist_** Although git says it's fine to delete the branch, I'm not sure whether that is true. Please enlight me....

**Comment by ajnelson-nist** [comment]
@plbt5 , yes, it's fine to delete a merged branch.

**Pull request merged**
